export const postData = [
  {
    id: 1,
    title: "Delicious Homemade Pizza Recipe",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "ChefMaster",
    userId: 1,

    postDate: "April 23,2024",
    description:
      "Learn how to make the perfect pizza at home with this easy recipe. It's a family favorite!",
  },
  {
    id: 2,

    title: "Exploring Nature: Hiking Trails Guide",
    images: ["https://via.placeholder.com/150"],
    user: "NatureLover23",
    userId: 2,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Discover the most beautiful hiking trails in your area with our comprehensive guide.",
  },
  {
    id: 3,
    author: "ahmed",
    title: "Cozy Winter Soup Recipes",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/10",
      "https://via.placeholder.com/1000",
      "https://via.placeholder.com/1500",
    ],
    user: "SoupMaster",
    userId: 3,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Warm up this winter with these delicious and comforting soup recipes.",
  },
  {
    id: 4,
    author: "ahmed",
    title: "DIY Home Decoration Ideas",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "DIYQueen",
    userId: 4,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Spruce up your living space with these creative DIY home decoration ideas.",
  },
  {
    id: 5,
    author: "ahmed",
    title: "Healthy Breakfast Recipes",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "HealthNut",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Start your day right with these nutritious and delicious breakfast recipes.",
  },
  {
    id: 6,
    author: "ahmed",
    title: "Traveling on a Budget: Tips and Tricks",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "BudgetExplorer",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Explore the world without breaking the bank with our budget-friendly travel tips.",
  },
  {
    id: 7,
    author: "ahmed",
    title: "Beginner's Guide to Yoga",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "YogaEnthusiast",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Start your journey to wellness with our beginner-friendly yoga guide.",
  },
  {
    id: 8,
    author: "ahmed",
    title: "Classic Movie Night: Must-Watch Films",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "MovieBuff",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Relive the golden age of cinema with our selection of classic must-watch films.",
  },
  {
    id: 9,
    author: "ahmed",
    title: "Gardening Tips for Beginners",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "GreenThumb",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Get your hands dirty and create a beautiful garden with our beginner-friendly gardening tips.",
  },
  {
    id: 10,
    author: "ahmed",
    title: "Quick and Easy Dinner Recipes",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "ChefExtraordinaire",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Whip up delicious dinners in no time with these quick and easy recipes.",
  },
  {
    id: 11,
    author: "ahmed",
    title: "Photography 101: Basics for Beginners",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Capture stunning moments with our beginner's guide to photography basics.",
  },
  {
    id: 12,
    author: "ahmed",
    title: "Refreshing Summer Drinks",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "ThirstQuencher",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Beat the heat with these refreshing summer drink recipes that will cool you down instantly.",
  },
  {
    id: 13,
    author: "ahmed",
    title: "Mindfulness Meditation Techniques",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "ZenMaster",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Achieve inner peace and tranquility with our mindfulness meditation techniques.",
  },
  {
    id: 14,
    author: "ahmed",
    title: "DIY Crafts for Kids",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "CraftyKids",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Keep your little ones entertained with these fun and creative DIY crafts for kids.",
  },
  {
    id: 15,
    author: "ahmed",
    title: "Fitness Tips for Busy Professionals",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
    user: "FitPro",
    userId: 1,
    publishDate: "April 23, 2000",
    postDate: "April 23,2024",
    description:
      "Stay in shape despite your busy schedule with our practical fitness tips for professionals.",
  },
];
