export const users = [
  {
    userId: 1,
    profilePhoto: "https://via.placeholder.com/150",
    userName: "john_doe",
    password: "password123",
    email: "john.doe@example.com",
    rating: 4.2,
    phoneNumber: "123-456-7890",
  },
  {
    userId: 2,
    profilePhoto: "https://via.placeholder.com/150",
    userName: "jane_smith",
    password: "letmein",
    email: "jane.smith@example.com",
    rating: 5,
    phoneNumber: "987-654-3210",
  },
  {
    userId: 3,
    profilePhoto: "https://via.placeholder.com/150",
    userName: "bob_jackson",
    password: "bob123",
    email: "bob.jackson@example.com",
    rating: 3,
    phoneNumber: "555-123-4567",
  },
  {
    userId: 4,
    profilePhoto: "https://via.placeholder.com/150",
    userName: "bobby",
    password: "1234",
    email: "abdabukarsh@gmail.com",
    rating: 3,
    phoneNumber: "555-123-4567",
  },
];
